---
# ======================================================================
# ReadTheDocs environment file
#
# If you wish to build a Mamba/Conda environment with the dependencies
# needed for building the ReadTheDocs documentation, use:
#
# $ conda env create -n rtd_env --file=read_the_docs_environment.yml
# ======================================================================
name: rtd_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python               =3.13
  - docutils             =0.21.2
  - jinja2               =3.1.6
  - myst-parser          =5.0.0
  - sphinx               =8.2.3
  - sphinx-autobuild     =2024.2.4
  - sphinx-rtd-theme     =3.1.0
  - sphinxcontrib-bibtex =2.6.5
